import { Property } from "./types";

export const mockProperties: Property[] = [
  {
    id: "prop-1",
    slug: "3-xonali-kvartira-6-mavze",
    title_uz: "3 xonali shinam kvartira",
    title_ru: "3-комнатная квартира",
    description_uz: "Angren shahrining 6-mavzesida joylashgan yorug‘ va qulay kvartira. Yevro ta'mirlangan, barcha qulayliklar mavjud.",
    description_ru: "Светлая и удобная квартира в 6-м микрорайоне Ангрена. Евроремонт, все коммуникации подключены, отличная планировка.",
    address_uz: "Angren, 6-mavze",
    address_ru: "Ангрен, 6-й микрорайон",
    district_name_uz: "6-mavze",
    district_name_ru: "6-й микрорайон",
    transaction_type: "sale",
    property_type: "apartment",
    status: "published",
    price_uzs: 520000000,
    price_usd: 40625,
    area_sqm: 72,
    rooms: 3,
    bathrooms: 1,
    floor: 3,
    total_floors: 5,
    renovation: "euro",
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1000&q=80",
    ],
    coordinates: {
      lat: 41.0182,
      lng: 70.1415,
    },
    utilities: {
      gas: true,
      water: true,
      sewerage: true,
      heating: true,
      electricity: true,
    },
    amenities: {
      furniture: true,
      parking: true,
      elevator: false,
      ac: true,
      balcony: true,
      internet: true,
    },
    contact_phone: "+998 90 123 45 67",
    contact_telegram: "angren_estate_admin",
    created_at: "2026-09-01T10:00:00Z",
  },
  {
    id: "prop-2",
    slug: "2-xonali-ijara-markaz",
    title_uz: "2 xonali zamonaviy kvartira",
    title_ru: "2-комнатная квартира",
    description_uz: "Angren markazida uzoq muddatga ijaraga beriladigan shinam, yangi jihozlangan kvartira.",
    description_ru: "Долгосрочная аренда уютной 2-комнатной квартиры в центре Ангрена. Вся необходимая мебель и бытовая техника.",
    address_uz: "Angren, markaz",
    address_ru: "Ангрен, центр",
    district_name_uz: "Markaz",
    district_name_ru: "Центр",
    transaction_type: "rent",
    property_type: "apartment",
    status: "published",
    price_uzs: 2500000,
    price_usd: 195,
    area_sqm: 56,
    rooms: 2,
    bathrooms: 1,
    floor: 4,
    total_floors: 9,
    renovation: "designer",
    images: [
      "https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1000&q=80",
    ],
    coordinates: {
      lat: 41.0125,
      lng: 70.1384,
    },
    utilities: {
      gas: true,
      water: true,
      sewerage: true,
      heating: true,
      electricity: true,
    },
    amenities: {
      furniture: true,
      parking: true,
      elevator: true,
      ac: true,
      balcony: true,
      internet: true,
    },
    contact_phone: "+998 93 555 12 34",
    contact_telegram: "angren_estate_admin",
    created_at: "2026-09-05T09:15:00Z",
  },
  {
    id: "prop-3",
    slug: "zamonaviy-xususiy-uy-dukent",
    title_uz: "Zamonaviy xususiy hovli-uy",
    title_ru: "Частный дом",
    description_uz: "Toza havo, 6 sotix yer, pishiq g‘ishtli zamonaviy fasadli shinam hovli.",
    description_ru: "Добротный современный дом на участке 6 соток. Просторный двор, панорамные окна, все коммуникации подключены.",
    address_uz: "Angren, Dukent massivi",
    address_ru: "Ангрен, массив Куйлюк",
    district_name_uz: "Dukent",
    district_name_ru: "Дукент",
    transaction_type: "sale",
    property_type: "house_yard",
    status: "published",
    price_uzs: 850000000,
    price_usd: 66406,
    area_sqm: 120,
    area_sotikh: 6,
    rooms: 4,
    bathrooms: 2,
    floor: 1,
    total_floors: 1,
    renovation: "euro",
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1000&q=80",
    ],
    coordinates: {
      lat: 41.0412,
      lng: 70.1654,
    },
    utilities: {
      gas: true,
      water: true,
      sewerage: true,
      heating: true,
      electricity: true,
    },
    amenities: {
      furniture: false,
      parking: true,
      elevator: false,
      ac: true,
      balcony: false,
      internet: true,
    },
    contact_phone: "+998 90 987 65 43",
    contact_telegram: "angren_estate_admin",
    created_at: "2026-09-03T14:30:00Z",
  },
  {
    id: "prop-4",
    slug: "2-xonali-kvartira-7-mavze",
    title_uz: "2 xonali yangi kvartira",
    title_ru: "2-комнатная квартира",
    description_uz: "7-mavzeda yangi ta'mirlangan qulay va shinam kvartira.",
    description_ru: "Качественная 2-комнатная квартира в 7-м микрорайоне. Новый ремонт, чистый подъезд, удобный выезд на центральную дорогу.",
    address_uz: "Angren, 7-mavze",
    address_ru: "Ангрен, 7-й микрорайон",
    district_name_uz: "7-mavze",
    district_name_ru: "7-й микрорайон",
    transaction_type: "sale",
    property_type: "apartment",
    status: "published",
    price_uzs: 420000000,
    price_usd: 32812,
    area_sqm: 54,
    rooms: 2,
    bathrooms: 1,
    floor: 5,
    total_floors: 9,
    renovation: "euro",
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1000&q=80",
    ],
    coordinates: {
      lat: 41.0289,
      lng: 70.1523,
    },
    utilities: {
      gas: true,
      water: true,
      sewerage: true,
      heating: true,
      electricity: true,
    },
    amenities: {
      furniture: true,
      parking: true,
      elevator: true,
      ac: true,
      balcony: true,
      internet: true,
    },
    contact_phone: "+998 90 777 88 99",
    contact_telegram: "angren_estate_admin",
    created_at: "2026-09-06T12:00:00Z",
  },
  {
    id: "prop-5",
    slug: "tijorat-markaz-arenda",
    title_uz: "Angren markazida tijorat binosi",
    title_ru: "Коммерческое помещение в центре",
    description_uz: "Aholisi gavjum ko‘chada, birinchi qavatda joylashgan shinam tijorat joyi. Do‘kon yoki ofis uchun tayyor.",
    description_ru: "Отличное коммерческое помещение на первой линии в центре Ангрена. Высокий пешеходный трафик, евроремонт.",
    address_uz: "Angren, Mustaqillik shoh ko‘chasi",
    address_ru: "Ангрен, проспект Мустакиллик",
    district_name_uz: "Markaz",
    district_name_ru: "Центр",
    transaction_type: "rent",
    property_type: "commercial",
    status: "published",
    price_uzs: 12000000,
    price_usd: 937,
    area_sqm: 140,
    rooms: 3,
    bathrooms: 1,
    floor: 1,
    total_floors: 4,
    renovation: "euro",
    images: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1000&q=80",
    ],
    coordinates: {
      lat: 41.0160,
      lng: 70.1450,
    },
    utilities: {
      gas: true,
      water: true,
      sewerage: true,
      heating: true,
      electricity: true,
    },
    amenities: {
      furniture: false,
      parking: true,
      elevator: false,
      ac: true,
      balcony: false,
      internet: true,
    },
    contact_phone: "+998 91 222 33 44",
    contact_telegram: "angren_estate_admin",
    created_at: "2026-09-07T15:00:00Z",
  },
  {
    id: "prop-6",
    slug: "3-xonali-yangi-bino-5-mavze",
    title_uz: "3 xonali shinam xonadon, 5-mavze",
    title_ru: "3-комнатная квартира, 5-й микрорайон",
    description_uz: "Angren 5-mavzesida joylashgan sokin va shinam kvartira. Maktab, bog‘cha va bozor yaqinida.",
    description_ru: "Уютная 3-комнатная квартира в 5-м микрорайоне Ангрена. Рядом школа, детский сад, транспортная развязка.",
    address_uz: "Angren, 5-mavze",
    address_ru: "Ангрен, 5-й микрорайон",
    district_name_uz: "5-mavze",
    district_name_ru: "5-й микрорайон",
    transaction_type: "sale",
    property_type: "apartment",
    status: "published",
    price_uzs: 380000000,
    price_usd: 29687,
    area_sqm: 65,
    rooms: 3,
    bathrooms: 1,
    floor: 2,
    total_floors: 5,
    renovation: "cosmetic",
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1000&q=80",
    ],
    coordinates: {
      lat: 41.0220,
      lng: 70.1330,
    },
    utilities: {
      gas: true,
      water: true,
      sewerage: true,
      heating: true,
      electricity: true,
    },
    amenities: {
      furniture: true,
      parking: true,
      elevator: false,
      ac: true,
      balcony: true,
      internet: true,
    },
    contact_phone: "+998 94 444 55 66",
    contact_telegram: "angren_estate_admin",
    created_at: "2026-09-08T11:20:00Z",
  },
];
